# Generated by Django 5.0.4 on 2024-05-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCordoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_placa', models.IntegerField()),
                ('cordao_fisico', models.CharField(max_length=255)),
                ('canal_placa', models.IntegerField()),
                ('sensor_placa', models.IntegerField()),
            ],
            options={
                'db_table': 'registro_cordoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroPlaca',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('ip', models.TextField()),
            ],
            options={
                'db_table': 'registro_placas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('password', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
